### ISSUE TITLE
delay_basic.h

### ISSUE THREAD

**Issue by DenniZr** [SodaqMoja/Sodaq_SoftSerial#1]
I get the errror:
#include <util/delay_basic.h> file missing.
In the arduino ide.
I'm trying this with the sodaq explorer

**Comment by 6sco** [comment]
Same for me.

**Comment by ainjayla** [comment]
Same here.

**Comment by tozenda** [comment]
Same here.

**Comment by SodaqMoja** [comment]
This library is a clone of SoftSerial and we only used it for AVR devices. Lately we are mostly working with SAMD devices which have enough UARTs. So for us there is no need to use this library anymore. That is why you don't see any activity here.
If you really want to use SoftSerial I advice you to go to https://github.com/PaulStoffregen/SoftwareSerial and see if that suits your needs.
